### ISSUE TITLE
once found dataset, how do you retrieve the eml?

### ISSUE THREAD

**Issue by seltmann** [Big-Bee-Network/bif#9]
https://linker.bio/zip:hash://sha256/b90a523c156babba2b495fa7ed67a9ad280d6cef585e0d4fbdc1f8c566cb57a8!/meta.xml
https://linker.bio/zip:hash://sha256/b90a523c156babba2b495fa7ed67a9ad280d6cef585e0d4fbdc1f8c566cb57a8!/eml.xml

**Comment by seltmann** [comment]
run by: 

`sh find-datasets-with-bees.sh 1>datasets.txt 2>datasets.log` 

runs in background and lists datasets that are skipped.

cat datasets.log | grep measurementOrFact.csv | grep -Eo "hash://sha256/[a-f0-9]{64}"

**Comment by jhpoelen** [comment]
After disabling the content cache, I was able to see:

```
curl https://linker.bio/zip:hash://sha256/b90a523c156babba2b495fa7ed67a9ad280d6cef585e0d4fbdc1f8c566cb57a8!/meta.xml\
 | head
```

and 

```
curl https://linker.bio/zip:hash://sha256/b90a523c156babba2b495fa7ed67a9ad280d6cef585e0d4fbdc1f8c566cb57a8!/eml.xml\
 | head
```
